language: python
python:
- 3.6.5
sudo: required
services:
  - docker
script:
  - sudo apt-get install -y moreutils
  - pip install twine bash-plus
  - bash-plus kube-provision | sponge kube-provision
  - python setup.py sdist
  - twine upload dist/*.tar.gz || echo already exists