containers:
  - image: "{{docker_proxy}}docker.io/consul:1.3.1"
    args: agent -ui -bootstrap -server
    docker_args: --net=host {% if not private_dns | is_empty %}--dns={{private_dns}}{% endif %}
    env:
      CONSUL_CLIENT_INTERFACE: "{{consul_bind_interface}}"
      CONSUL_BIND_INTERFACE: "{{consul_bind_interface}}"
commands:
  - iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-ports 8500