env_vars:
  ETCDCTL_ENDPOINTS: https://127.0.0.1:2379
  ETCDCTL_CACERT: /etc/kubernetes/pki/etcd/ca.crt
  ETCDCTL_CERT: /etc/kubernetes/pki/etcd/healthcheck-client.crt
  ETCDCTL_KEY: /etc/kubernetes/pki/etcd/healthcheck-client.key
  KUBECONFIG: /etc/kubernetes/admin.conf

files:
  /etc/kubernetes/consul/api.json: "{{cluster_name}}/api.json"
  /etc/kubernetes/pki/etcd/ca.crt: "{{cluster_name}}/certs/etcd/ca.crt"
  /etc/kubernetes/pki/etcd/ca.key: "{{cluster_name}}/certs/etcd/ca.key"
  /etc/kubernetes/pki/front-proxy-ca.crt: "{{cluster_name}}/certs/front-proxy-ca.crt"
  /etc/kubernetes/pki/front-proxy-ca.key: "{{cluster_name}}/certs/front-proxy-ca.key"
  /etc/kubernetes/pki/sa.key: "{{cluster_name}}/certs/sa.key"
  /etc/kubernetes/pki/sa.pub: "{{cluster_name}}/certs/sa.pub"
  /etc/kubernetes/pki/ca.crt: "{{cluster_name}}/certs/ca.crt"
  /etc/kubernetes/pki/ca.key: "{{cluster_name}}/certs/ca.key"